# -*- coding: utf-8 -*-
"""Facial_Detection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AGxn7xhC1jFdSe1OrtKlCe-Dd2MuVw_e
"""
from facenet_pytorch import MTCNN
import cv2
from PIL import Image
import numpy as np
from matplotlib import pyplot as plt

import torch

class Detection:
  def __init__(self):
    pass
    
  def detect(self, img_path):
    self.img = cv2.imread(img_path)
    frame = cv2.cvtColor(self.img, cv2.COLOR_BGR2RGB)
    self.frame = Image.fromarray(frame)
    mtcnn = MTCNN(image_size = 224, margin=40, keep_all=True, post_process=False, device=torch.device("cuda:0" if torch.cuda.is_available() else "cpu"))
    faces = mtcnn(self.frame)
    faces_1 = faces.permute(0, 2, 3, 1).int().numpy()
    return faces_1

